### PR TITLE
Better (IMHO) icon :-)

### PR DESCRIPTION
**Pull request by vjr**
Use the `computer` icon instead of `application-x-firmware` which looks less busy to my tired old eyes.

### CODE REVIEW

**Comment by vjr** [comment]
Screenshots:

Before:

about-before

After:

about-after

**Comment by danirabbit** [comment]
I'm not sure this works because of the possible confusion with display settings. I think I'm :-1: here sorry

**Comment by vjr** [comment]
No worries - do you have an alternative icon in mind? Or I can just close this PR.

**Comment by danirabbit** [comment]
Not really I like the current icon :sweat_smile:

**Comment by vjr** [comment]
alrighty then!

**Pull request closed without merging**
