### PR TITLE
Added support for Epiphany in Report a Problem

### PR DESCRIPTION
**Pull request by KeironO**
This pull request aims to resolve https://github.com/elementary/switchboard-plug-about/issues/85.

### CODE REVIEW

**Comment by cassidyjames** [comment]
@danrabbit thoughts on this? It makes sense to me but does add a little but of noise, but reduces cleverness. Which is probably fine?

**Comment by cassidyjames** [comment]
An alternative would be to set a GitHub string const if we wanted to reduce repetition there, but that also just adds some complexity. Maybe specifying an entire URL is fine.

**Comment by arshubham** [comment]
@KeironO Can a identifier be added to see if issue is a github/gitlab or Other url. This will help to solve https://github.com/elementary/switchboard-plug-about/issues/69 . Based on type of url github/gitlab api can be used to send user info.

**Comment by KeironO** [comment]
> @KeironO Can a identifier be added to see if issue is a github/gitlab or Other url. This will help to solve #69 . Based on type of url github/gitlab api can be used to send user info.

Hey @arshubham,

I have been unable to find any documentation from either GitHub or Gitlab that outlines that such functionality exists. If you can direct me to it, I would have no issue in attempting to resolve said issue.

**Comment by arshubham** [comment]
Can't this endpoint be used https://developer.github.com/v3/issues/#create-an-issue ? Just send an empty string as a title and body with the user info.

**Comment by arshubham** [comment]
Can't this endpoint be used https://developer.github.com/v3/issues/#create-an-issue ? Just send an empty string as a title and body with the user info.

**Comment by peteruithoven** [comment]
I would focus this PR on adding Epiphany (gitlab) support. Maybe a separate PR could be opened to work on #69? 
@arshubham maybe you could add those tips to #69?

**Comment by KeironO** [comment]
I'll get to work on this this weekend.

**Pull request merged**
